---
title: "ESM 206 Assignment 4"
author: "Cameryn Brock and Allie Hacker"
date: "11/6/2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE, warning=FALSE}

# Attach packages

library(tidyverse)
library(janitor)

# Read in & clean up data

lobster_data <- read_csv("lobster_abundance_sbc_lter.csv", 
                         na = "-99999") %>% 
  clean_names()

# Tidy data by uncounting counts

lobster_tidy <- lobster_data %>% 
  uncount(count)

# Add MPA column to data
lobster_mpa <- lobster_tidy %>% 
  mutate(mpa= ifelse(site %in% c("IVEE", "NAPL"), "MPA", "non-MPA" ))

```
#### Introduction

To be written

#### Data and Methods

To be written

#### Results
```{r}
# Part A: Changes in annual lobster abundance by site

#get annual count of lobsters for each site
lobster_abundance <- lobster_tidy %>% 
  count(site, year) %>% 
  mutate(mpa= ifelse(site %in% c("IVEE", "NAPL"), "MPA", "non-MPA" ))

# graph lobster abundance

ggplot(lobster_abundance, 
       aes(x = year, 
           y = n, 
           group = site, 
           color = mpa, 
           size = mpa)
       )+
  geom_line()+
  scale_color_manual(values = c("cyan4", "gray"))+
  scale_size_manual(values = c(1.2, 0.5))+
  theme(legend.title = element_blank(),
        legend.position = c(2012.5, 900)
        )+
  theme_minimal()+
  labs(x= "Year", y = "Lobsters observed")+
  scale_x_continuous(breaks = seq(2012, 2018, 1), expand = c(0,0))+
  scale_y_continuous(breaks = seq(0, 1010, 200))+
  coord_cartesian(clip = 'off')+
  annotate("text", 
           x = 2018.05, 
           y = 946, 
           label = "Isla Vista", 
           size = 3, 
           hjust = 0)+
  annotate("text", 
           x = 2018.05, 
           y = 290, 
           label = "Naples", 
           size = 3, 
           hjust = 0)+
  annotate("text", 
           x = 2018.05, 
           y = 164, 
           label = "Mohawk", 
           size = 3, 
           hjust = 0)+
  annotate("text", 
           x = 2018.05, 
           y = 355, 
           label = "Carpenteria", 
           size = 3, 
           hjust = 0)+
  annotate("text", 
           x = 2018.05, 
           y = 54, 
           label = "Arroyo Quemado", 
           size = 3, 
           hjust = 0)

```
**Figure 1. California Spiny Lobster abundance in Santa Barbara Channel (2012-2018)** 

